datasource:
  url: https://raw.githubusercontent.com/mcnoreau/backend-coding-challenge/master/data/cities_canada_usa.tsv
  columns:
    id: id
    name: name
    ascii: ascii
    alt_name: alternativeName
    lat: latitude
    long: longitude
    feat_class: featClass
    feat_code: featCode
    country: country
    cc2: cc2
    admin1: admin1
    admin2: admin2
    admin3: admin3
    admin4: admin4
    population: population
    elevation: elevation
    dem: demography
    tz: timeZone
    modified_at: modifiedAt
