datasource:
  name: cities_canada-usa.tsv
  columns:
    name:
      pos: 2
      type: String
    ascii:
      pos: 3
      type: String
    alt_name:
      pos: 4
      type: List of String
      separator: ,
    lat:
      pos: 5
      type: Double
    long:
      pos: 6
      type: Double
    country:
      pos: 9
      type: String
    admin1:
      pos: 11
      type: String
    population:
      pos: 15
      type: BigInt
codes:
  CA: Canada
    admin1:
      01: Alberta
      02: British Columbia
      03: Manitoba
      04: New Brunswick
      13: Northwest Territories
      07: Nova Scotia
      14: Nunavut
      08: Ontario
      09: Prince Edward Island
      10: Quebec
      11: Saskatchewan
      12: Yukon
      05: Newfoundland and Labrador
  US: United States
    admin1:
      AR: Arkansas
      DC: Washington, D.C.
      DE: Delaware
      FL: Florida
      GA: Georgia
      KS: Kansas
      LA: Louisiana
      MD: Maryland
      MO: Missouri
      MS: Mississippi
      NC: North Carolina
      OK: Oklahoma
      SC: South Carolina
      TN: Tennessee
      TX: Texas
      WV: West Virginia
      AL: Alabama
      CT: Connecticut
      IA: Iowa
      IL: Illinois
      IN: Indiana
      ME: Maine
      MI: Michigan
      MN: Minnesota
      NE: Nebraska
      NH: New Hampshire
      NJ: New Jersey
      NY: New York
      OH: Ohio
      RI: Rhode Island
      VT: Vermont
      WI: Wisconsin
      CA: California
      CO: Colorado
      NM: New Mexico
      NV: Nevada
      UT: Utah
      AZ: Arizona
      ID: Idaho
      MT: Montana
      ND: North Dakota
      OR: Oregon
      SD: South Dakota
      WA: Washington
      WY: Wyoming
      HI: Hawaii
      AK: Alaska
      KY: Kentucky
      MA: Massachusetts
      PA: Pennsylvania
      VA: Virginia